export const dataTes = [
  {
    id: 't1',
    question:
      'W. M. Stanley adalah sarjana Amerika yang sangat berjasa dalam perkembangan virologi, karena dia adalah orang pertama yang berhasil....',
    options: [
      {id: 1, answer: 'Mengamati struktur virus', selected: false},
      {
        id: 2,
        answer: 'Menyaring virus dengan saringan porselin',
        selected: false,
      },
      {id: 3, answer: 'Membiakkan virus di dalam medium', selected: false},
      {
        id: 4,
        answer: 'Mengisolasi dan mengkristalkan virus',
        correct: true,
        selected: false,
      },
      {id: 5, answer: 'Membiakkan virus dalam embrio burung', selected: false},
    ],
    answer: 'D. Mengisolasi dan mengkristalkan virus',
    selected: false,
    image: null,
  },
  {
    id: 't2',
    question:
      'Sifat virus yang menunjukkan cirinya sebagai makhluk hidup adalah kemampuannya untuk...',
    options: [
      {
        id: 1,
        answer: 'Memasuki jaringan',
        selected: false,
      },
      {id: 2, answer: 'Mengikat O2', selected: false},
      {id: 3, answer: 'Dapat dikristalkan', selected: false},
      {id: 4, answer: 'Bergerak aktif', selected: false},
      {id: 5, answer: 'Bereproduksi', correct: true, selected: false},
    ],
    answer: 'E. Bereproduksi',
    selected: false,
    image: null,
  },
  {
    id: 't3',
    question: 'Perhatikan gambar berikut! Kapsid ditunjukkan pada nomor....',
    options: [
      {id: 1, answer: '1', selected: false},
      {id: 2, answer: '2', correct: true, selected: false},
      {id: 3, answer: '3', selected: false},
      {id: 4, answer: '4', selected: false},
      {id: 5, answer: '5', selected: false},
    ],
    answer: 'B. 2',
    selected: false,
    image: require('../assets/image/tes.png'),
  },
  {
    id: 't4',
    question: 'Tahap-tahap daur litik yang benar adalah....',
    options: [
      {
        id: 1,
        answer: 'Adsorpsi – injeksi – litik – perakitan – sintesis',
        selected: false,
      },
      {
        id: 2,
        answer: 'Adsorpsi – perakitan – sintesis – litik – injeksi',
        selected: false,
      },
      {
        id: 3,
        answer: 'Adsorpsi – injeksi – sintesis – perakitan – litik',
        correct: true,
        selected: false,
      },
      {
        id: 4,
        answer: 'Adsorpsi – injeksi – sintesis – litik – perakitan',
        selected: false,
      },
      {
        id: 5,
        answer: 'Adsorbsi – sintesis – injeksi – perakitan – litik',
        selected: false,
      },
    ],
    answer: 'C. Adsorpsi – injeksi – sintesis – perakitan – litik',
    selected: false,
    image: null,
  },
  {
    id: 't5',
    question: 'Fase yang tidak terdapat pada daur litik adalah....',
    options: [
      {id: 1, answer: 'Sintesis', selected: false},
      {id: 2, answer: 'Perakitan', selected: false},
      {id: 3, answer: 'Injeksi', selected: false},
      {id: 4, answer: 'Penggabungan', correct: true, selected: false},
      {id: 5, answer: 'Adsorbsi', selected: false},
    ],
    answer: 'D. Penggabungan',
    selected: false,
    image: null,
  },
  {
    id: 't6',
    question: 'Virus yang mempunyai asam nukleat RNA adalah virus....',
    options: [
      {id: 1, answer: 'HIV', selected: false},
      {id: 2, answer: 'Cacar', selected: false},
      {id: 3, answer: 'Hepatitis', selected: false},
      {id: 4, answer: 'Influenza', correct: true, selected: false},
      {id: 5, answer: 'Herpes', selected: false},
    ],
    answer: 'D. Influenza',
    selected: false,
    image: null,
  },
  {
    id: 't7',
    question:
      'Penyakit-penyakit yang disebabkan oleh virus di bawah ini ialah ....',
    options: [
      {
        id: 1,
        answer: 'Cacar, influenza, demam berdarah',
        correct: true,
        selected: false,
      },
      {id: 2, answer: 'Cacar, antraks, disentri', selected: false},
      {id: 3, answer: 'Cacar, tifus, demam berdarah', selected: false},
      {id: 4, answer: 'Cacar, antraks, demam berdarah', selected: false},
      {id: 5, answer: 'Antraks, tifus, malaria', selected: false},
    ],
    answer: 'A. Cacar, influenza, demam berdarah',
    selected: false,
    image: null,
  },
  {
    id: 't8',
    question: 'Manfaat virus bagi kehidupan manusia adalah....',
    options: [
      {id: 1, answer: 'Fermentasi dan vaksin', selected: false},
      {id: 2, answer: 'Antibiotik dan vaksin', selected: false},
      {id: 3, answer: 'Vaksin dan penelitian genetika', selected: false},
      {id: 4, answer: 'Antibiotik dan penelitian genetika ', selected: false},
      {id: 5, answer: 'Antitoksin dan vaksin', correct: true, selected: false},
    ],
    answer: 'E. Antitoksin dan vaksin',
    selected: false,
    image: null,
  },
  {
    id: 't9',
    question: 'Perbedaan antara Ribovirus dan Deoksiribovirus adalah....',
    options: [
      {id: 1, answer: 'Kepala', selected: false},
      {id: 2, answer: 'Ekor', selected: false},
      {id: 3, answer: 'Isi', selected: false},
      {id: 4, answer: 'Asam nukleatnya', correct: true, selected: false},
      {id: 5, answer: 'Kapsid', selected: false},
    ],
    answer: 'D. Asam nukleatnya',
    selected: false,
    image: null,
  },
  {
    id: 't10',
    question:
      'Virus dalam melakukan replikasi, virus akan mengambil alih fungsi dna bakteri untuk....',
    options: [
      {
        id: 1,
        answer: 'Menghancurkan dinding sel bakteri (lisis)',
        selected: false,
      },
      {
        id: 2,
        answer: 'Melaksanakan sintesis protein dan membuat struktur virus baru',
        correct: true,
        selected: false,
      },
      {id: 3, answer: 'Membuat DNA versi baru', selected: false},
      {
        id: 4,
        answer: 'Mengaktifkan inti sel inang untuk memproduksi enzim baru',
        selected: false,
      },
      {
        id: 5,
        answer: 'Melumpuhkan inang agar tidak bisa bereproduksi',
        selected: false,
      },
    ],
    answer: 'B. Melaksanakan sintesis protein dan membuat struktur virus baru',
    selected: false,
    image: null,
  },
];
